### PR TITLE
Change minifying engine to closure compiler

### PR DESCRIPTION
**Pull request by gmetais**
Closure compiler complains a little during the build.
```
WARNING - If this if/for/while really shouldn't have a body, use {}
```

This empty loop is the reason:
```js
for (var i = this.length; i-- && this[i] !== value;) {}
```

But it works!

### CODE REVIEW

**Comment by vvo** [comment]
AWESOME!

**Comment by kapouer** [comment]
I probably won't until the day i'll package it for debian :)
Note that
`uglifyjs lazyload.js -c -m --mangle-props > lazyload.min.js`
gives a lazyload.min.js of 3579 bytes with latest version.
I'm not sure if mangle-props is safe, though.

**Comment by vvo** [comment]
> gives a lazyload.min.js of 3819 bytes with latest version.

So is this better than closure?

**Comment by kapouer** [comment]
3819 - 3788 = 31 bytes...
since i don't have a working web page under my fingers with lazyload.min.js that i can test,
i don't know if this version works. The command-line to get this level of compression is given above.

**Pull request merged**
